POST http://127.0.0.1:8000/opt HTTP/1.1
content-type: application/json

{
    "p": [{
        "dEdy": 6000.0,
        "dEdx": 30.0,
        "LE": 0.0,
        "angle": 36.0,
        "UW": 0.0,
        "d2Edx2": 0.0,
        "UP": -3.08190346928009,
        "LW": 0.0,
        "bias": 1019.0,
        "LP": 3.08190346928009,
        "UE": 0.0,
        "deEdy2": 0.0
    }]
}